### ISSUE TITLE
Add video capability to PI scatterplot hover

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#323]
Enable mp4 video files to be played in the PI model.  The mp4 files must already exist (no conversions from a set of images).  As with image inputs to the model, a column of full path descriptors for the video files must be included in the CSV input file.  The model will include video columns with the image columns in the drop down menu for selecting which images to view during hover events.  If a video column is selected, the hover event will pop up the first frame of the video with the standard triangle play icon in the center.  Pressing play will start streaming the animation.

**Comment by alexsielicki** [comment]
An initial version of this is ready. It will pull the video using agents and will display it inside the bubble using a <video> tag. Controls are there for play, pause, seek, etc. There are still issues with dragging the bubble around and other event handlers that are getting in the way. Also, it downloads the entire video before playing, so no streaming yet. Video column is specified as an "image"' column on model creation and the client identifies the video by the response header content-type, so there's no explicit way to specify a video column yet. This is on master.

**Comment by alexsielicki** [comment]
Dragging, pinning, and resizing of the video bubble should now work with no problems. The video height is reduced to prevent it from covering the close, pin, and resize icons because unlike images, videos take up the top layer and have clickable controls which interfere with ours. This reduced size also provides an area above and below the video that you can use to drag the bubble. With images you can drag the whole bubble by dragging the image, but with videos you have to use the white areas above and below because clicking the video causes it to play. I might be able to make the video draggable, but thought we should try this first and see if it works.

**Comment by alexsielicki** [comment]
Just fixed issues with restoring video bubbles on models that had them open and are bookmarked and reloaded. Still issues with Chrome. Still need to use getFile instead of getImage api to download video file.

**Comment by alexsielicki** [comment]
using file api for videos, image api for images

**Comment by pjcross** [comment]
The issue with the color-coding of the video is only present in Firefox on Windows 7, and only on the first play through.  Outside of slycat, the video plays correctly on Windows 7 (Chrome, Explorer) and OSX (Safari, Firefox, and Chrome).

**Comment by alexsielicki** [comment]
Video capabilities are now working, tested under OSX and Windows, Firefox and Chrome. If we still have problems with video encoding, let's open a new issue for that.
