### ISSUE TITLE
Double image displayed during hover (Firefox on Windows, Chrome on OS X)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#426]
During hover, two copies of the image appear in the same frame.
![image](https://cloud.githubusercontent.com/assets/4998608/7636630/99e8cb10-fa25-11e4-8837-7c936932dcd8.png)

**Comment by pjcross** [comment]
This is directly linked to the problem of a double login dialog popping up.  When I performed the login twice (entered my password into each dialog), I got a double image in a single frame.  Since login acted as a gate for the operation, as I finished the first login I got a regular single image in the frame.  However, after the 2nd login, the two images were combined.

**Comment by alexsielicki** [comment]
I looked at this a bit and though I don't understand the problem fully, it might be due to recent work on server side image caching. It's clear that the code that loads images is being called twice in rapid succession, perhaps due to window.setTimeout not being managed correctly. You can see console.log messages that indicate the double image load since they list the same image twice.

**Comment by FadingSwordsman** [comment]
After testing this more, I think this is now fixed. A window.clearTimeout was missing in one of the event handlers, which would allow multiple hovers on the same node (And therefore multiple logins and images).

I've condensed the handlers a bit and added a separate function for resetting the hover timer.

**Comment by pjcross** [comment]
This is not fixed.  I am still seeing it.

**Comment by pjcross** [comment]
I'm still seeing this bug...

**Comment by pjcross** [comment]
I can't reproduce this now, so I've closed it.
