### ISSUE TITLE
remote file system default directory

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#439]
Perhaps the users home directory should be the initial default directory when browsing for a remote file (such as when creating a cca model from a remote file). The users home directory perhaps does not have the highest probability of containing the desired file, however, the current default (root or "/") can cause the process to completely hang if one of the mounted mass storage systems is un-responsive. In this case, the file retrieval is completely blocked until the stat on root responds. If the initial default directory is the users home, the user can still navigate through his home files and any other responding directories without waiting for the root problem to clear.

**Comment by pjcross** [comment]
Since the client remembers where you were the last time you created a model, starting from root only happens the first time you create a remote model on a particular machine or if you clear your cache.  So starting from your home directory will have little impact.  A better solution would be to allow the user to type in a path as an alternative to walking the directory structure.  That way, if a particular disk were unresponsive, the user could manually enter a path to an alternative directory.

**Comment by pjcross** [comment]
Now we have a type-in interface in addition to the directory view.
