### ISSUE TITLE
Weird behavior when editing project (Firefox & Chrome on Windows)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#440]
When editing the project, if I click on the project members (the colored buttons with the user ids), the names disappear.  To see if I was actually somehow removing project members in this way, I tried saving the project.  Happily, it did not remove anyone, but provided the following message:

Alert

Error updating project. Forbidden

However, it seems to me that this behavior will be confusing to users and should be eliminated.

**Comment by FadingSwordsman** [comment]
To clarify:
As a project administrator, I can add/remove users in the method described above
As a project writer or reader, I cannot add or remove users, nor can I change the title or description of the project

As a writer or reader, I should not see the Edit Project option, since I don't have access to actually change anything.

**Comment by FadingSwordsman** [comment]
Even more clarification:
It's not explicit that clicking on a user's name is deleting that user.
It is also possible to remove yourself currently, which shouldn't be allowed.

In both cases, a warning that requires confirmation should be displayed.

**Comment by FadingSwordsman** [comment]
Between 0385d99 and b622b0f, I believe this is done:
* Added a separate popup for viewing project information.
* Separated delete button and username icon.
* Added explicit tooltip to remove user button.
* Added dialog to warn user if they were removing themselves as an administrator.
