### ISSUE TITLE
Need logout mechanism

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#542]
I want to be able to explicitly logout of Slycat.  When demoing on other people's machines, I want to be sure that my access and credentials are terminated when I'm done.

**Comment by pjcross** [comment]
I'm imaging it as a drop down option from the username.

**Comment by Mletter1** [comment]
reference http://tools.cherrypy.org/wiki/RestfulAuth

**Comment by Mletter1** [comment]
may turn logout function into part of the authentication tool

**Comment by Mletter1** [comment]
After discussion with Tim we will need to move away from basic auth and create our own custom authentication method in order for us to be able to have a proper log-out mechanism

**Comment by alexsielicki** [comment]
@Mletter1, I did a little more testing after you left and it turns out that signout only breaks if you use the back button after canceling. So:
1. Click Sign Out
2. Click Cancel
3. Click Back button
4. Sign back in
5. Click Sign Out
6. Problem: you just go to projects page instead of being signed out.

However:
1. Click Sign Out
2. Click Cancel
3. Click Reload button
4. Sign back in
5. Click Sign Out
6. No Problem: you are prompted to sign in again.

**Comment by Mletter1** [comment]
Closed by eee2a1d, 21b0df9, and 850c05e
