### ISSUE TITLE
Filter buttons should change color instead of darken on hover

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#788]
A customer is having trouble with his mental model of the button functions in filters.  He expects that when he pushes a button, it will select that item.  Part of the problem is that in hovering over a button, the button color darkens to highlight it, which suggests selection.  Instead, the button should highlight with the opposite color (grey if the button is blue, or blue if the button is grey).  This provides a better cue that clicking the button will disable (for initially blue buttons) or enable (for initially grey buttons) that value.

**Comment by alexsielicki** [comment]
This is now finished but I had to work around an unforeseen problem. When hovering over a blue category button, the button would turn gray per our discussion to signify that clicking it will disable it. However, once clicked, the button's state changes to "inactive" (i.e., gray), and the mouse pointer is still hovering it, thus applying the blue color effect because now clicking it would turn it on. The effect was that clicking on a blue button would turn it blue, and clicking a gray button would turn it gray. Not what we wanted. So I added code to change the color of blue buttons to gray immediately after the click, and gray buttons to blue. Once the user's mouse leaves the button, the hover effect changes and blue buttons turn gray again while gray turn blue. This might be much easier to demo than describe. But I think I got it right after some extra work.
