### ISSUE TITLE
Add functionality to capture high-quality image output

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#813]
Multiple customers have requested publication quality image output.

**Comment by alexsielicki** [comment]
Some tools I found:
http://html2canvas.hertzen.com
https://www.npmjs.com/package/html-to-image

**Comment by Mletter1** [comment]
@pjcross @alexsielicki is this invalidated, did we determine we cannot do this?

**Comment by alexsielicki** [comment]
It became complicated to do it in high resolution since the client would need to regenerate the scatterplot canvas using the higher resolution, then combine it with the rest of the UI. I think @Spurs20 tried a few JS libraries but they didn't provide any higher resolution output when compared to a normal screenshot. From what I remember we put it on hold.

**Comment by pjcross** [comment]
The cost vs benefit is too low.  We won't do this.
